dep cleanup fixes
shipstation/terraform-provider-teamcity pull request #8
Opened 2019-03-01 00:18 UTC by jeremygaither

2019-03-01 03:44 UTC, jeremygaither commented
Actually, I’m not sure this is the right way. Maybe `vendor/` should be in gitignore? But adding the source and branch properties to Gopkg means that file cannot be shared between forks. If everything was using `$GOPATH/src/` then changing git remotes would suffice, but dep doesn’t seem to handle things that way.

2019-03-01 14:42 UTC, ss-remygreinhofer requested changes

2019-03-01 14:42 UTC, ss-remygreinhofer commented on Gopkg.toml
> +  name = "github.com/cvbarros/go-teamcity-sdk"
Why would you add the repo from cvbarros back? it does not work with our version of the provider anymore?

2019-03-01 14:42 UTC, ss-remygreinhofer commented on Gopkg.toml
> +  source = "../go-teamcity-sdk"
The `source` has to be relative to your $GOPATH, it cannot be anywhere you want.

2019-03-01 14:55 UTC, ss-remygreinhofer commented on Gopkg.toml
> +  source = "../go-teamcity-sdk"
Scratch that, it is the repo on github..., nothing to do with the file system.

2019-03-02 20:13 UTC, jeremygaither commented
Not the right way to solve this problem. Go build and dep seem to have different rules, which seems very odd... further research needed.

2019-03-02 20:13 UTC, closed without merging